apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-todoapp
  labels:
    app: capstone-todoapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-todoapp
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-todoapp
    spec:
      containers:
        - image: pvpuno/todoapp
          imagePullPolicy: Always
          name: capstone-todoapp
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-todoapp
  labels:
    app: capstone-todoapp
spec:
  type: LoadBalancer
  selector:
    app: capstone-todoapp
  ports:
    - name: http
      protocol: TCP
      port: 31000
      targetPort: 3000
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443