apiVersion: v1
kind: Service
metadata:
  name: capstone-todoapp
  labels:
    app: capstone-todoapp
spec:
  type: LoadBalancer
  selector:
    app: capstone-todoapp
  ports:
    - port: 30000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP